import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#b5b4ba',
        'tertiary-fixed-dim': '#c5c6cf',
        secondary: '#c7c6cb',
        'on-tertiary-fixed-variant': '#45464e',
        'on-secondary': '#2f3035',
        outline: '#938ea1',
        'on-tertiary': '#2e3038',
        'inverse-primary': '#603ce2',
        'primary-fixed': '#e6deff',
        background: '#051424',
        'secondary-container': '#46464b',
        'surface-container-high': '#1c2b3c',
        'surface-container-lowest': '#010f1f',
        'surface-variant': '#273647',
        'tertiary-fixed': '#e2e2ec',
        'on-surface-variant': '#c9c4d8',
        'on-primary': '#31009a',
        'primary-fixed-dim': '#cabeff',
        'primary-container': '#947dff',
        surface: '#051424',
        primary: '#cabeff',
        electric: '#7C5CFF',
        'on-tertiary-fixed': '#191b22',
        'on-primary-container': '#2a0088',
        tertiary: '#c5c6cf',
        'on-surface': '#d4e4fa',
        error: '#ffb4ab',
        'tertiary-container': '#8f9099',
        'surface-bright': '#2c3a4c',
        'on-secondary-fixed-variant': '#46464b',
        'on-primary-fixed-variant': '#4816cb',
        'on-error': '#690005',
        'surface-container-highest': '#273647',
        'surface-container-low': '#0d1c2d',
        'on-background': '#d4e4fa',
        'surface-container': '#122131',
        'on-tertiary-container': '#282931',
        'on-primary-fixed': '#1c0062',
        'inverse-surface': '#d4e4fa',
        'surface-dim': '#051424',
        'surface-tint': '#cabeff',
        'secondary-fixed-dim': '#c7c6cb',
        'secondary-fixed': '#e3e2e7',
        'error-container': '#93000a',
        'on-secondary-fixed': '#1a1b20',
        'outline-variant': '#484555',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#233143',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-gap': '64px',
        gutter: '24px',
        unit: '8px',
        'container-padding-mobile': '20px',
        'container-padding-desktop': '40px',
      },
      fontFamily: {
        rubik: ['Rubik', 'sans-serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        'headline-md': ['Montserrat'],
        'body-lg': ['Inter'],
        'display-lg': ['Montserrat'],
        'label-sm': ['Geist'],
        'display-lg-mobile': ['Montserrat'],
        'body-md': ['Inter'],
        'mono-data': ['Geist'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'mono-data': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}

export default config
