-- AlterTable
ALTER TABLE "Product" ADD COLUMN "visible" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Service" ADD COLUMN "visible" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Article" ADD COLUMN "visible" BOOLEAN NOT NULL DEFAULT true;
